import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import axios from 'axios'
import {io} from 'socket.io-client'
import {
  Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, ChevronDown, ChevronRight,
  CircleGauge, Cpu, Download, Droplets, Factory, Gauge, Grid2X2, Info, LayoutDashboard,
  Menu, Network, Radio, RefreshCw, Settings, ShieldCheck, Thermometer, Waves, Zap,
  FlaskConical, BatteryCharging, Database, FileText, MapPin, Clock3, LockKeyhole,
  ServerCog, ArrowUpRight, CircleDot
} from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000'
const fmt=(v,d=1)=>Number(v??0).toFixed(d)
const time=v=>v?new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'--:--:--'

function Login({onLogin}) {
 const [mode,setMode]=useState('login'),[email,setEmail]=useState('admin@urjawave.local'),[password,setPassword]=useState('ChangeMe123!'),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const url=mode==='login'?`${API}/api/v1/auth/login`:`${API}/api/v1/auth/register`;const r=await axios.post(url,mode==='login'?{email,password}:{email,name,password});localStorage.setItem('uw_token',r.data.token);axios.defaults.headers.common.Authorization=`Bearer ${r.data.token}`;onLogin(r.data.user)}catch(e){setError(e.response?.data?.error||'Authentication failed')}finally{setBusy(false)}};
 return <div className="loginScreen"><div className="loginCard"><div className="brand"><div className="brandmark"><Waves size={24}/></div><div><strong>UrjaWave</strong><span>H₂ MONITORING PLATFORM</span></div></div><div className="eyebrow">SECURE OPERATIONS CONSOLE</div><h1>{mode==='login'?'Welcome back':'Create viewer account'}</h1><p>Industrial hydrogen-generation telemetry and safety intelligence.</p>{error&&<div className="errorbar"><AlertTriangle size={15}/>{error}</div>}<form onSubmit={submit}>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" required/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" required/><input type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="primary" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in securely':'Create account'}</button></form><button className="switchAuth" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create a viewer account':'Back to sign in'}</button><small>Demo admin: admin@urjawave.local · ChangeMe123!</small></div></div>
}

function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[menu,setMenu]=useState(false),[overview,setOverview]=useState(null),[history,setHistory]=useState([]),[devices,setDevices]=useState([]),[alerts,setAlerts]=useState([]),[connected,setConnected]=useState(false),[lastUpdate,setLastUpdate]=useState(null),[error,setError]=useState('')
 const [authChecked,setAuthChecked]=useState(false);
 useEffect(()=>{const t=localStorage.getItem('uw_token');if(!t){setAuthChecked(true);return}axios.defaults.headers.common.Authorization=`Bearer ${t}`;axios.get(`${API}/api/v1/auth/me`).then(r=>setUser(r.data.user)).catch(()=>{localStorage.removeItem('uw_token');delete axios.defaults.headers.common.Authorization}).finally(()=>setAuthChecked(true))},[]);
 const load=async()=>{try{const [a,b,c,d]=await Promise.all([axios.get(`${API}/api/v1/overview`),axios.get(`${API}/api/v1/telemetry?limit=90`),axios.get(`${API}/api/v1/devices`),axios.get(`${API}/api/v1/alerts`)]);setOverview(a.data);setHistory(b.data.data||[]);setDevices(c.data.data||[]);setAlerts(d.data.data||[]);setLastUpdate(new Date());setError('')}catch(e){setError('Backend unavailable — start the UrjaWave API on port 5000')}}
 useEffect(()=>{if(!user)return;load();const s=io(API,{transports:['websocket','polling'],auth:{token:localStorage.getItem('uw_token')}});s.on('connect',()=>setConnected(true));s.on('disconnect',()=>setConnected(false));s.on('snapshot',x=>setHistory(x||[]));s.on('telemetry',x=>{setHistory(v=>[...v,x].slice(-90));setOverview(v=>v?{...v,latest:x}:v);setLastUpdate(new Date())});s.on('alert',x=>setAlerts(v=>[x,...v].slice(0,100)));return()=>s.close()},[])
 const latest=overview?.latest||history.at(-1)||{}
 const active=alerts.filter(a=>!a.acknowledged)
 const health=useMemo(()=>{const checks=[latest.pressure<=18,latest.temperature<=82,latest.efficiency>=65,latest.phLevel>=6.5&&latest.phLevel<=7.8];return Math.round(checks.filter(Boolean).length/4*100)},[latest])
 const nav=[['dashboard','Mission Control',LayoutDashboard],['analytics','Performance',BarChart3],['process','Process Overview',Network],['assets','Field Assets',Cpu],['alerts','Safety & Events',Bell],['reports','Reports',FileText],['settings','Configuration',Settings]]
 const ack=async id=>{try{await axios.post(`${API}/api/v1/alerts/${id}/acknowledge`);setAlerts(v=>v.map(a=>a.id===id?{...a,acknowledged:true}:a))}catch{}}
 if(!authChecked)return <div className="loginScreen"><div className="loginCard"><div className="eyebrow">URJAWAVE</div><h1>Authenticating…</h1></div></div>; if(!user)return <Login onLogin={setUser}/>;
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}>
   <div className="govbar"><span className="flag saffron"/><span className="flag white"/><span className="flag green"/><span className="govtext">PUBLIC ENERGY TECHNOLOGY PROGRAMME</span></div>
   <div className="brand"><div className="brandmark"><Waves size={24}/></div><div><strong>UrjaWave</strong><span>H₂ MONITORING PLATFORM</span></div></div>
   <div className="programme"><div className="seal"><Factory size={19}/></div><div><b>Hydrogen Generation</b><span>R&amp;D TECHNOLOGY DEMONSTRATOR</span></div></div>
   <div className="sideLabel">OPERATIONS</div>
   <nav>{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><I size={18}/><span>{label}</span>{page===id&&<ChevronRight size={14}/>}</button>)}</nav>
   <div className="sideBottom"><div className="security"><ShieldCheck size={17}/><div><b>SECURE CONSOLE</b><span>Telemetry integrity enabled</span></div></div><div className="version">UW-H2 / DIGITAL MONITORING / 2.0</div></div>
  </aside>
  <main className="main">
   <header className="topbar"><button className="hamb" onClick={()=>setMenu(!menu)}><Menu/></button><div className="breadcrumb"><span>URJAWAVE</span><ChevronRight size={13}/><b>{nav.find(x=>x[0]===page)?.[1]}</b></div><div className="topActions"><span className={connected?'link online':'link'}><span className="pulse"/>{connected?'LIVE TELEMETRY':'LINKING'}</span><span className="mode"><CircleDot size={12}/> {overview?.plant?.operatingMode||'DEMO'}</span><button className="refresh" onClick={load}><RefreshCw size={15}/></button><div className="operator"><div className="avatar">{(user.name||"UW").slice(0,2).toUpperCase()}</div><div><b>{user.name}</b><span>{user.role.toUpperCase()}</span></div><button className="logout" onClick={()=>{localStorage.removeItem("uw_token");delete axios.defaults.headers.common.Authorization;setUser(null)}}>Logout</button></div></div></header>
   {error&&<div className="errorbar"><AlertTriangle size={15}/>{error}<button onClick={load}>Retry</button></div>}
   <div className="page"><div className="roleNotice"><ShieldCheck size={13}/> Authenticated · <b>{user.role}</b> · audit trail enabled</div>{page==='dashboard'&&<Dashboard latest={latest} history={history} health={health} alerts={active} connected={connected} lastUpdate={lastUpdate}/>} {page==='analytics'&&<Analytics history={history}/>} {page==='process'&&<Process latest={latest}/>} {page==='assets'&&<Assets devices={devices} connected={connected}/>} {page==='alerts'&&<Alerts alerts={alerts} ack={ack}/>} {page==='reports'&&<Reports/>} {page==='settings'&&<Config/>}</div>
   <footer><span><ShieldCheck size={12}/> UrjaWave H₂ Monitoring Platform · Technology demonstration</span><span>Telemetry <b>{time(lastUpdate)}</b> · System <b>{connected?'ONLINE':'OFFLINE'}</b></span></footer>
  </main>
 </div>
}

function Dashboard({latest,history,health,alerts,connected,lastUpdate}){return <>
 <section className="missionHead"><div className="titleBlock"><div className="eyebrow"><span/> HYDROGEN TECHNOLOGY · DIGITAL OPERATIONS LAYER</div><h1>Hydrogen Generation<br/><em>Mission Control</em></h1><p>Integrated monitoring for electrolyzer performance, process safety, water quality and electrical efficiency.</p><div className="meta"><span><MapPin size={13}/> Hydrogen Generation Bay</span><span><Clock3 size={13}/> Updated {time(lastUpdate)}</span><span><Database size={13}/> Telemetry window: 90 points</span></div></div><div className="missionCard"><div className="mcTop"><div><span>PLANT STATUS</span><b>OPERATIONAL</b></div><div className="statusIcon"><CheckCircle2/></div></div><div className="healthNumber"><strong>{health}%</strong><span>system health</span></div><div className="healthBar"><i style={{width:`${health}%`}}/></div><div className="healthFoot"><span>Safety envelope</span><b>{connected?'LIVE':'WAITING'}</b></div></div></section>
 <section className="sectionHead"><div><div className="eyebrow">LIVE TELEMETRY</div><h2>Core Generation Parameters</h2></div><div className="sectionRight"><span className="sample"><span/>2 sec refresh</span><button className="outline" onClick={()=>{fetch(`${API}/api/v1/report.csv`,{headers:{Authorization:`Bearer ${localStorage.getItem('uw_token')}`}}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='urjawave-h2-telemetry.csv';a.click();URL.revokeObjectURL(u)})}}><Download size={14}/> Export CSV</button></div></section>
 <div className="metrics"> <Metric label="Hydrogen Production" value={fmt(latest.hydrogenFlow,2)} unit="Nm³/h" Icon={Activity} accent="cyan" sub="Generation rate"/><Metric label="System Pressure" value={fmt(latest.pressure,2)} unit="bar" Icon={Gauge} accent="blue" sub="Process pressure"/><Metric label="Stack Temperature" value={fmt(latest.temperature,1)} unit="°C" Icon={Thermometer} accent="amber" sub="Electrolyzer stack"/><Metric label="Water Quality" value={fmt(latest.phLevel,2)} unit="pH" Icon={Droplets} accent="violet" sub="Process water"/><Metric label="DC Power" value={fmt(latest.voltage*latest.current/1000,2)} unit="kW" Icon={Zap} accent="green" sub={`${fmt(latest.voltage,1)} V · ${fmt(latest.current,1)} A`}/><Metric label="System Efficiency" value={fmt(latest.efficiency,1)} unit="%" Icon={CircleGauge} accent="teal" sub="Energy conversion"/></div>
 <div className="dashboardGrid"><Trend history={history}/><Safety alerts={alerts}/></div>
 <ProcessStrip latest={latest}/>
 </>}

function Metric({label,value,unit,Icon,accent,sub}){return <div className={`metric ${accent}`}><div className="metricTop"><div className="metricIcon"><Icon size={18}/></div><span className="metricLive">LIVE</span></div><span className="metricLabel">{label}</span><div className="metricValue">{value}<small>{unit}</small></div><span className="metricSub">{sub}</span><i className="metricLine"/></div>}

function Trend({history}){const vals=history.map(x=>Number(x.hydrogenFlow)||0);const min=Math.min(...vals,7),max=Math.max(...vals,9),pts=vals.map((v,i)=>`${i/(Math.max(vals.length-1,1))*100},${94-(v-min)/(max-min||1)*74}`).join(' ');return <div className="panel trend"><div className="panelHead"><div><div className="eyebrow">PRODUCTION INTELLIGENCE</div><h3>Hydrogen Generation Trend</h3><span>Recent telemetry stream · Nm³/h</span></div><div className="trendNow"><b>{fmt(vals.at(-1),2)}</b><span>Nm³/h</span><small>current output</small></div></div><div className="chart"><div className="ylabels"><span>{max.toFixed(1)}</span><span>{((max+min)/2).toFixed(1)}</span><span>{min.toFixed(1)}</span></div><div className="gridlines"><i/><i/><i/><i/></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#22c8b6" stopOpacity=".28"/><stop offset="1" stopColor="#22c8b6" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${pts} 100,100`} fill="url(#fill)"/><polyline points={pts}/></svg></div><div className="xlabels"><span>−60 min</span><span>−45</span><span>−30</span><span>−15</span><span>NOW</span></div></div>}

function Safety({alerts}){return <div className="panel safety"><div className="panelHead"><div><div className="eyebrow">PROCESS SAFETY</div><h3>Safety Event Monitor</h3></div><span className={alerts.length?'badge danger':'badge good'}>{alerts.length?`${alerts.length} ACTIVE`:'ALL CLEAR'}</span></div>{alerts.length?<div className="alertList">{alerts.slice(0,5).map(a=><div className="alertItem" key={a.id}><div className="alertIcon"><AlertTriangle size={16}/></div><div><b>{a.message}</b><span>{a.deviceId} · {time(a.timestamp)} · {a.severity.toUpperCase()}</span></div></div>)}</div>:<div className="allClear"><div><ShieldCheck size={31}/></div><b>No active safety events</b><span>Operating parameters are within configured limits.</span><small>Last evaluation: {new Date().toLocaleTimeString('en-IN')}</small></div>}</div>}

function ProcessStrip({latest}){return <section className="panel processStrip"><div className="processTitle"><div className="eyebrow">PROCESS VISIBILITY</div><h3>Electrolyzer Operating Chain</h3><span>Digital representation of the monitored hydrogen generation pathway</span></div><div className="flow"><Node icon={Droplets} title="Water Feed" value={`${fmt(latest.phLevel,2)} pH`} state="Within band"/><div className="connector"/><Node icon={FlaskConical} title="Electrolyzer" value={`${fmt(latest.temperature,1)} °C`} state="Operating"/><div className="connector"/><Node icon={Waves} title="H₂ Separation" value={`${fmt(latest.pressure,2)} bar`} state="Stable"/><div className="connector"/><Node icon={BatteryCharging} title="Power System" value={`${fmt(latest.efficiency,1)} %`} state="Efficient"/><div className="connector"/><Node icon={Factory} title="H₂ Output" value={`${fmt(latest.hydrogenFlow,2)} Nm³/h`} state="Generating"/></div></section>}
function Node({icon:Icon,title,value,state}){return <div className="node"><div className="nodeIcon"><Icon size={17}/></div><span>{title}</span><b>{value}</b><small><span/> {state}</small></div>}

function Page({kicker,title,children,action}){return <><section className="pageTitle"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>Hydrogen technology monitoring and operational intelligence.</p></div>{action}</section>{children}</>}
function Analytics({history}){const avg=k=>history.length?history.reduce((s,x)=>s+(Number(x[k])||0),0)/history.length:0;return <Page kicker="OPERATIONS INTELLIGENCE" title="Performance Analytics"><div className="analyticsCards"><Metric label="Avg. H₂ Production" value={fmt(avg('hydrogenFlow'),2)} unit="Nm³/h" Icon={Activity} accent="cyan" sub="Telemetry average"/><Metric label="Avg. Efficiency" value={fmt(avg('efficiency'),1)} unit="%" Icon={CircleGauge} accent="teal" sub="Energy conversion"/><Metric label="Avg. Pressure" value={fmt(avg('pressure'),2)} unit="bar" Icon={Gauge} accent="blue" sub="Process average"/></div><Trend history={history}/><div className="panel intelligence"><BarChart3/><div><b>Operational intelligence layer</b><span>Compare generation rate with pressure, temperature and electrical load to identify stable operating windows before physical plant integration.</span></div></div></Page>}
function Process({latest}){return <Page kicker="PLANT PROCESS" title="Process Overview"><ProcessStrip latest={latest}/><div className="processCards"><div className="panel infoCard"><div className="bigIcon"><Network/></div><b>Integrated telemetry chain</b><span>Field sensors → gateway → validation → safety rules → operator console.</span></div><div className="panel infoCard"><div className="bigIcon"><ShieldCheck/></div><b>Safety evaluation</b><span>Pressure, temperature, water quality and efficiency are evaluated continuously.</span></div><div className="panel infoCard"><div className="bigIcon"><ServerCog/></div><b>Digital operations</b><span>Designed as a software layer around real hydrogen-generation hardware.</span></div></div></Page>}
function Assets({devices,connected}){return <Page kicker="ASSET MANAGEMENT" title="Field Assets"><div className="assetGrid">{devices.map(d=><div className="panel asset" key={d.deviceId}><div className="assetTop"><div className="assetIcon"><Cpu/></div><span className="badge good">{connected?'ONLINE':'STANDBY'}</span></div><b>{d.name}</b><small>{d.deviceId}</small><div className="assetRow"><span>Type</span><b>{d.type}</b></div><div className="assetRow"><span>Location</span><b>{d.location}</b></div><div className="assetRow"><span>Last seen</span><b>{time(d.lastSeen)}</b></div></div>)}</div></Page>}
function Alerts({alerts,ack}){return <Page kicker="SAFETY OPERATIONS" title="Safety & Events"><div className="panel eventPanel"><div className="panelHead"><div><div className="eyebrow">EVENT REGISTER</div><h3>Alarm and notification history</h3></div><span className={alerts.filter(a=>!a.acknowledged).length?'badge danger':'badge good'}>{alerts.filter(a=>!a.acknowledged).length} ACTIVE</span></div>{alerts.length?alerts.map(a=><div className={`event ${a.severity}`} key={a.id}><div className="alertIcon"><AlertTriangle size={17}/></div><div><b>{a.message}</b><span>{a.deviceId} · {new Date(a.timestamp).toLocaleString('en-IN')}</span></div>{!a.acknowledged&&<button onClick={()=>ack(a.id)}>Acknowledge</button>}</div>):<div className="allClear large"><ShieldCheck size={38}/><b>No recorded safety events</b><span>The event register is currently clear.</span></div>}</div></Page>}
function Reports(){const download=()=>{fetch(`${API}/api/v1/report.csv`,{headers:{Authorization:`Bearer ${localStorage.getItem('uw_token')}`}}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='urjawave-h2-telemetry.csv';a.click();URL.revokeObjectURL(u)})};return <Page kicker="DATA & REPORTING" title="Reports"><div className="reportHero panel"><div className="reportIcon"><FileText/></div><div><div className="eyebrow">TELEMETRY EXPORT</div><h3>Hydrogen Generation Telemetry Report</h3><p>Export the current server-side telemetry register for analysis, documentation and project reporting.</p><button className="primary" onClick={download}><Download size={15}/> Download CSV Report</button></div></div><div className="reportGrid"><div className="panel reportItem"><Database/><b>Machine-readable telemetry</b><span>Timestamped production, pressure, temperature, water quality and electrical readings.</span></div><div className="panel reportItem"><FileText/><b>Project documentation</b><span>Structured outputs suitable for technical review and demonstration reporting.</span></div><div className="panel reportItem"><ShieldCheck/><b>Safety traceability</b><span>Event records can be acknowledged and retained as part of the operations workflow.</span></div></div></Page>}
function Config(){return <Page kicker="SYSTEM GOVERNANCE" title="Configuration"><div className="configGrid"><div className="panel config"><div className="configIcon"><Radio/></div><div><b>Telemetry source</b><p>DEMO mode provides deterministic demonstration data. LIVE HARDWARE mode is reserved for field gateway integration.</p></div><span className="badge neutral">DEMO READY</span></div><div className="panel config"><div className="configIcon"><LockKeyhole/></div><div><b>Operator access</b><p>Production deployments should use authenticated operator roles, audit logging and least-privilege access.</p></div><span className="badge good">DESIGNED</span></div><div className="panel config"><div className="configIcon"><ShieldCheck/></div><div><b>Safety thresholds</b><p>Server-side checks monitor pressure, temperature, pH and efficiency against configured limits.</p></div><span className="badge good">ACTIVE</span></div></div></Page>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
